### ISSUE TITLE
CI/CD 파이프라인 구축 및 S3, CodeDeploy 연동

### ISSUE THREAD

**Issue by lov-etan** [Pay-phone/payphone-backend#12]
### 백엔드 CI/CD 파이프라인 구축 및 S3, CodeDeploy 연동

---

### 이슈 설명
현재 GitHub Actions를 활용하여 백엔드의 지속적인 통합(CI)과 배포(CD)을 구현 중입니다. 이슈는 다음의 세부 작업들을 포함하며, 자동화된 배포를 목표로 설정된 CI/CD 워크플로우에 대한 개선 사항을 다룹니다.

---

#### **CI 작업**
1. **MySQL 컨테이너 설정**
   - GitHub Actions에서 MySQL 도커 컨테이너를 설정하여 테스트 환경 구성.
2. **Maven 테스트 및 빌드**
   - `mvn clean test`를 통해 단위 테스트를 실행.
   - `mvn clean package`를 사용하여 `.jar` 파일 생성.

#### **CD 작업**
1. **S3 버킷 생성 및 연동**
   - S3 버킷(`payphone-backend-deploy`)에 빌드된 `.jar` 파일 업로드.
2. **CodeDeploy 애플리케이션 및 배포 그룹 구성**
   - CodeDeploy를 사용하여 EC2에 `.jar` 파일을 배포.
   - EC2 인스턴스에 CodeDeploy 에이전트 설치 및 IAM 역할 설정.
3. **GitHub Actions와 AWS 통합**
   - GitHub Secrets를 활용하여 S3 및 CodeDeploy 연동에 필요한 환경 변수 설정.
   - CodeDeploy 배포 트리거 추가.

---

### 작업 체크리스트
- [x] MySQL 도커 컨테이너를 사용하여 CI 환경 구성.
- [x] Maven으로 테스트 및 빌드 수행.
- [x] S3 버킷에 `.jar` 파일 업로드.
- [x] CodeDeploy를 사용하여 EC2 서버에 자동 배포.
- [x] GitHub Actions에 CI/CD 워크플로우 통합.
- [ ] AppSpec 파일 및 시작 스크립트 작성.
- [ ] 모니터링 및 배포 로그 확인 기능 추가.

---

### 참고 사항
1. **CodeDeploy와 EC2 설정**
   - CodeDeploy가 EC2 인스턴스와 통신하기 위한 IAM 역할 필요(`AWSCodeDeployRole`).
   - EC2 인스턴스에 태그 추가(`Key=Project, Value=PayphoneBackend`).

2. **GitHub Actions 주요 설정**
   ```yaml
   - name: Upload Jar to S3
     uses: jakejarvis/s3-sync-action@v0.5.1
     with:
       args: --acl public-read
   ```

3. **AppSpec 파일**
   ```yaml
   version: 0.0
   os: linux
   files:
     - source: /
       destination: /home/ec2-user/payphone-backend
   hooks:
     AfterInstall:
       - location: deploy-scripts/start-server.sh
         timeout: 300
         runas: ec2-user
   ```

4. **CI/CD 워크플로우 요약**
   - CI: GitHub Actions에서 MySQL 컨테이너와 Maven을 활용한 테스트 및 빌드.
   - CD: S3 업로드 → CodeDeploy 트리거 → EC2 배포.

---

### 기대 효과
- 백엔드 애플리케이션의 **지속적인 테스트 및 배포 자동화**.
- AWS S3와 CodeDeploy를 활용한 안정적인 배포 프로세스.
- EC2 서버 관리 간소화 및 신뢰성 향상.
